# JDK 1.7.0_51 Docker image is based off taylodl/centos:6.5
FROM taylodl/centos:6.5

MAINTAINER Don Taylor https://hub.docker.com/u/taylodl

# Add Java and setup Java environment
ADD jdk-7u51-linux-x64.tar.gz /appl/java/

ENV JAVA_HOME /appl/java/jdk1.7.0_51
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/appl/java/jdk1.7.0_51/bin


