FROM taylodl/centos
VOLUME /appl/oracle/middleware/wls/wls12120/user_projects/domains/mydomain/autodeploy
CMD echo mounted container volume /appl/oracle/middleware/wls/wls12120/user_projects/domains/mydomain/autodeploy

